version: 2.1

orbs:
  python: circleci/python@2.1.1


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
        environment:
          FLASK_ENV: testing
          SECRET_KEY: dummy_secret_key
          DATABASE_URL: postgresql://root@postgres/circle_test
      - image: cimg/postgres:14.1
        name: postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
        command: -p 5433

    executor:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install additional dependencies
          command: |
            pip install psycopg2-binary
      - run:
          name: Install additional dependencies
          command: |
            pip install pytest pytest-cov coveralls
      - run:
          name: Wait for PostgreSQL
          command: |
            dockerize -wait tcp://localhost:5433 -timeout 1m
      - run:
          name: Run tests
          command: |
            pytest tests/ --cov=./ --cov-report=xml
      - run:
          name: Upload coverage to Coveralls
          command: |
            pip install coveralls
            coveralls
          environment:
            COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
            COVERALLS_SERVICE_NAME: circleci

workflows:
  test-workflow:
    jobs:
      - build-and-test