version: 2.1

orbs:
  python: circleci/python@2.1.1


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
        environment:
          FLASK_ENV: testing
          CIRCLECI: true
          SECRET_KEY: 'dhytersgasdass'
          DATABASE_URL: postgresql://root@postgres/circle_test
      - image: cimg/postgres:14.1
        name: postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
        command: -p 5433

    executor:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install additional dependencies
          command: |
            pip install psycopg2-binary
      - run:
          name: Install dockerize
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
            rm dockerize-linux-amd64-v0.6.1.tar.g
      - run:
          name: Install additional dependencies
          command: |
            pip install pytest pytest-cov coveralls
      - run:
          name: Wait for PostgreSQL
          command: |
            dockerize -wait tcp://postgres:5433 -timeout 2m

      - run:
          command: |
            docker-compose exec postgres psql -U root -d circle_test -c 'SELECT 1;'
      - run:
          name: Run tests
          command: |
            pytest tests/ --cov=./ --cov-report=xml
      - run:
          name: Upload coverage to Coveralls
          command: |
            pip install coveralls
            coveralls
          environment:
            COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
            COVERALLS_SERVICE_NAME: circleci

workflows:
  test-workflow:
    jobs:
      - build-and-test