version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    executor:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dependencies
          command: |
            pip install pytest pytest-cov coveralls
      - run:
          name: Run tests with coverage
          command: |
            pytest --cov=./ --cov-report=xml
      - run:
          name: Upload coverage to Coveralls
          command: |
            coveralls
          environment:
            COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
            COVERALLS_SERVICE_NAME: circleci

workflows:
  sample:
    jobs:
      - build-and-test